export const SET_DATE = Symbol("SET_DATE");
export const FETCH_CITY_WEATHER_REQUEST = Symbol("FETCH_CITY_WEATHER_REQUEST");
export const FETCH_CITY_WEATHER_SUCCESS = Symbol("FETCH_CITY_WEATHER_SUCCESS");
export const FETCH_CITY_WEATHER_FAILURE = Symbol("FETCH_CITY_WEATHER_FAILURE");
